name: auto-rec
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pip=19.2.3=py37_0
  - python=3.7.4
  - pytorch=1.2.0=py3.7_cuda9.2.148_cudnn7.6.2_0
  - setuptools=41.2.0=py37_0
  - torchvision=0.4.0=py37_cu92
  - wheel=0.33.6=py37_0
  - matplotlib
  - pip:
    - jupyter-client==5.3.3
    - jupyter-core==4.5.0
    - jupyterlab==1.1.4
    - jupyterlab-server==1.0.6
    - matplotlib==3.1.1
    - packaging==19.2
    - pandas==0.25.1
    - pandas-profiling==2.3.0
    - scikit-learn==0.21.3
    - scikit-surprise==1.1.0
    - scipy==1.3.1
    - seaborn==0.9.0
    - sklearn==0.0
    - surprise==0.1
    - tqdm==4.36.1
